name: Auto Vote Script

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python with cache
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"   # 🔥 zapne pip cache

      - name: Install dependencies
        run: |
          pip install selenium

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run script
        run: python index.py
